[project]
name = "ml-implementation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kaggle>=2.0.0",
    "torch>=2.10.0",
    "torchvision>=0.25.0",
]
